version: 2.1
workflows:
  integration_tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:13
      - image: circleci/mongo:4.2.2

    working_directory: ~/quotable

    environment:
      MONGODB_URI: mongodb://localhost:27017/test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Seeding database
          command: npm run -s database:seed data/sample

      - run:
          name: Running ESLint
          command: npm run lint

      - run:
          name: Running tests
          command: npm run test
